spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: abc123456